apiVersion: v1
kind: ServiceAccount
metadata:
  name: platform-actor
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: platform-actor
  namespace: modern-core
rules:
- apiGroups: ["apps"]
  resources: ["replicasets"]
  verbs: ["get", "list"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "patch"]
  resourceNames: ["modern-core"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: platform-actor
  namespace: modern-core
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: platform-actor
subjects:
- kind: ServiceAccount
  name: platform-actor
  namespace: kube-system
